import PlayListService from "api/playlists.api";
import ProfileService from "api/profiles.api";
import { useQuery } from "react-query";
import { useDispatch } from "react-redux";
import { setToastMessageAction } from "redux/reducers/toast.reducer";
import { GetPlaylistaudiosRequest, GetPlaylistsRequest, GetPlaylistsTotalCountRequest } from "types/interfaces/requests/playlists-requests.interfaces";

export const useFetchPlaylistsByProfile = (payload?: GetPlaylistsRequest) => {
  const dispatch = useDispatch();
  const query = useQuery(["playlists-by-profile", payload], {
    queryFn: () => PlayListService.getPlayListsByProfileApi(payload!),
    onError: (error: any) => {
      dispatch(setToastMessageAction({ message: error.message, type: "error" }));
    },
  });

  return query;
};

export const useFetchPlaylistAudios = (payload: GetPlaylistaudiosRequest) => {
  const dispatch = useDispatch();
  const query = useQuery(["playlists-audios", payload], {
    queryFn: () => PlayListService.getPlaylistAudiosApi(payload),
    onError: (error: any) => {
      dispatch(setToastMessageAction({ message: error.message, type: "error" }));
    },
  });

  return query;
};

export const useFetchPLaylistsTotalCount = (payload: GetPlaylistsTotalCountRequest) => {
  const dispatch = useDispatch();
  const query = useQuery(["playlists-total-count", payload], {
    queryFn: () => PlayListService.getPlayListsTotalCountApi(payload!),
    onError: (error: any) => {
      dispatch(setToastMessageAction({ message: error.message, type: "error" }));
    },
  });

  return query;
};

export const useFetchAutoGeneratedPlaylists = () => {
  const dispatch = useDispatch();

  const query = useQuery(["playlists-auto-generated"], {
    queryFn: () => ProfileService.getAutoGeneratedPlaylists(),
    onError: (error: any) => {
      dispatch(setToastMessageAction({ message: error.message, type: "error" }));
    },
  });

  return query;
};
